CREATE TABLE [dbo].[User]
(
	[UserKey] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    [FirstName] NVARCHAR(64) NOT NULL, 
    [MiddleName] NVARCHAR(64) NULL, 
    [LastName] NVARCHAR(64) NOT NULL,
    [BirthDate] DATE NULL,

    -- Audit Data
    [CreatedBy] NVARCHAR(128) NOT NULL DEFAULT SUSER_NAME(),
    [UpdatedBy] NVARCHAR(128) NOT NULL DEFAULT SUSER_NAME(),
	[CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(), 
    [UpdatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    [RowStart] datetime2 (2) GENERATED ALWAYS AS ROW START HIDDEN,
    [RowEnd] datetime2 (2) GENERATED ALWAYS AS ROW END HIDDEN,
    PERIOD FOR SYSTEM_TIME ([RowStart], [RowEnd]) 
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [History].[dbo_User]));